version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce:latest
    command: --admin-password-file '/run/secrets/portainer-pwd'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
    networks:
      - traefik
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "app=portainer"
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`portainer.localhost`)"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        - "traefik.docker.network=traefik"
    secrets:
      - portainer-pwd

networks:
  traefik:
    name: traefik
    external: true

volumes:
  portainer-data:

secrets:
  portainer-pwd:
    external: true