- name: Setup docker swarm manager
  gather_facts: yes
  hosts: all

  vars:
    SWARM_MANAGER_ADDRESS: "192.168.0.100:2377"
    SWARM_JOIN_TOKEN_FILE: /assets/docker-swarm-join-token

  tasks:
    - name: Setup docker swarm
      docker_swarm:
        advertise_addr: "{{ SWARM_MANAGER_ADDRESS }}"
        listen_addr: "{{ SWARM_MANAGER_ADDRESS }}"
        state: present

    - name: Add node labels
      docker_node:
        hostname: manager
        labels:
          db: host